version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    container_name: nextjs-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE}
    depends_on:
      - db
    networks:
      - my-app-net

  command-runner:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    env_file:
      - .env
    environment:
      - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE}
    depends_on:
      - db
    networks:
      - my-app-net
    command:
      [
        "echo",
        "Command runner ready. Use 'docker-compose run' to execute commands.",
      ]

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=siswasiswa
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my-app-net

networks:
  my-app-net:
    driver: bridge

volumes:
  mysql-data:
    driver: local
